version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run:
          name: Install packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip python-dev  \
                          build-essential libssl-dev libffi-dev \
                          libxml2-dev libxslt1-dev zlib1g-dev python2.7 python-pip -y

      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            npm install
            zip -r lambda_function.zip index.js package.json node_modules/
            mv lambda_function.zip codedeploy_artifact/
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 sync codedeploy_artifact s3://${CODE_DEPLOY_S3}
      - run:
          name: Creat lambda stack
          command: |
            cd ./scripts/
            sh csye6225-aws-cf-create-lambda-stack.sh\
                        --stack csye-lambda\
                        --S3bucketName=${CODE_DEPLOY_S3}\
                        --DomainName=${DomainName}
      - run:
          name:
          command: |
            aws lambda update-function-code\
                   --region ${AWS_REGION}\
                   --function-name SendEmail\
                   --s3-bucket=${CODE_DEPLOY_S3}\
                   --s3-key lambda_function.zip\
