version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9.0-jessie
    steps:
      - checkout

      - run:
          name: Install packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip python-dev  \
              build-essential libssl-dev libffi-dev \
              libxml2-dev libxslt1-dev zlib1g-dev python2.7 python-pip -y

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Build Artifact
          command: |
            cd webapp
            pwd
            ls -al
            npm install
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            cp index.js codedeploy_artifact/
            zip -r deploy.zip index.js package.json node_modules/
            mv lambda_function.zip codedeploy_artifact/
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 sync codedeploy_artifact s3://${CODE_DEPLOY_S3}
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy"
      - run:
          name: Create Deployment
          command: |
            echo "Hello CodeDeploy"
            aws deploy create-deployment\
              --region ${AWS_REGION}\
              --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE\
              --application-name csye6225-lambda\
              --deployment-config-name CodeDeployDefault.OneAtATime\
              --deployment-group-name csye6225-lambda-deployment\
              --s3-location bucket=${CODE_DEPLOY_S3},bundleType=zip,key=lambda_function.zip